import sys
import random

def printInputError():
    print('$ python gen_random_graph_ER.py (1) (2) (3) (4)')
    print('(1) : name of the output file')
    print('(2) : random seed')
    print('(3) : number of vertices')
    print('(4) : ratio of generating edges')
    sys.exit()


# input parameters
if len(sys.argv) < 5 : printInputError()

outFile = open(sys.argv[1], 'w') # output file
random.seed(int(sys.argv[2]))
NoV = int(sys.argv[3]) # number of vertices
NoE = float(sys.argv[4]) # number of edges

if NoV < 0 : printInputError()
if NoE < 0 or NoE > 1 : printInputError()


# generate the graph
edgeList = []

for i in range(1, NoV) :
    for j in range(i + 1, NoV + 1) :
        r = random.random()
        if r < NoE :
            edgeList.append([i, j])



# write the output file
outFile.write('c generated by Erdos-Renyi model\n')
outFile.write('p edge {} {}\n'.format(NoV, len(edgeList)))
for edge in edgeList :
    outFile.write('{} 1 {}\n'.format(edge[0], edge[1]))
